# Generated by Django 3.2.11 on 2022-05-23 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RobotProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped')], max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'info'), ('error', 'error')], max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('cpu_usage', models.FloatField()),
                ('cpu_total', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('ram_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.robotprocess')),
            ],
            options={
                'ordering': ['-created_at', '-process__created_at'],
            },
        ),
    ]
