# Generated by Django 4.0.4 on 2022-05-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_log_type_processlog_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
