# Generated by Django 4.0.4 on 2022-05-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'value', 'size')},
        ),
    ]
